version: '3.3'

services:
  wordpress:
    container_name: ${DOCKER_CONTAINER_PREFIX}_srv
    depends_on:
       - db
    image: wordpress:4.9.4-apache
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp:/var/www/html/
    links:
      - db:db

  db:
    container_name: ${DOCKER_CONTAINER_PREFIX}_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db:/var/lib/mysql
      - ./db-conf:/etc/mysql/mariadb.conf.d/
      - ./logs:/var/log

  phpmyadmin:
    container_name: ${DOCKER_CONTAINER_PREFIX}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - /sessions
